// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using flightApp.Models;

namespace flightApp.Migrations
{
    [DbContext(typeof(FlightContext))]
    [Migration("20190906232107_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("flightApp.Models.Flight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class");

                    b.Property<decimal>("Price");

                    b.Property<DateTime>("arrivalTime");

                    b.Property<string>("departure");

                    b.Property<DateTime>("departureTime");

                    b.Property<string>("destination");

                    b.HasKey("ID");

                    b.ToTable("flight");
                });
#pragma warning restore 612, 618
        }
    }
}
